load("@com_google_protobuf//:protobuf.bzl", "cc_proto_library")
load("@com_github_grpc_grpc//:bazel/grpc_build_system.bzl", "grpc_cc_library")
load("@com_github_grpc_grpc//:bazel/grpc_build_system.bzl", "grpc_proto_library")

grpc_proto_library(
    name = 'hello',
    srcs = [ 'hello.proto' ])

